spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopdev
    username: root
    password: binguyen221198
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

app:
  accessTokenSecret: UPmFVTfAGDB0LgWanUtVgJMYgZLTCBTkqbZb63k4ySdCs4k7m0F/3Whlk5G5g/6vMqO3IDXiXDipSc4U2kP//w==
  accessTokenExpiration: 3600